PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE LIVRE (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  PAGES		 TEXT	 NOT NULL,  EDITEUR	 TEXT	 NOT NULL, ISEMPRUNT	 BOOLEAN);
INSERT INTO "LIVRE" VALUES('L_étranger','Albert Camus','1942','001','185','Gallimard','true');
INSERT INTO "LIVRE" VALUES('Le Rouge et le Noir','Stendhal','1830','002','453','Levasseur',NULL);
INSERT INTO "LIVRE" VALUES('Madame Bovary','Gustave Flaubert','1857','003','479','Michel Lévy frères',NULL);
INSERT INTO "LIVRE" VALUES('Divergente','Veronica Roth','2014','210','445','Nathan',NULL);
INSERT INTO "LIVRE" VALUES('Il est de retour','Timur Vermes','2011','006','404','10-18',NULL);
CREATE TABLE VIDEO (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  DUREE		 TEXT	 NOT NULL,  PAYS		 TEXT	 NOT NULL, ISEMPRUNT	 BOOLEAN);
INSERT INTO "VIDEO" VALUES('Le Roi Lion','Roger Allers, Rob Minkoff','1994','016','1h29','Américain','true');
INSERT INTO "VIDEO" VALUES('Intouchables','Eric Toledano, Olivier Nakache','2011','017','1h52','Français','true');
INSERT INTO "VIDEO" VALUES('Le Seigneur des anneaux : la communauté de l_anneau','Peter Jackson','2001','014','2h45','Américain, Néo-zélandais',NULL);
INSERT INTO "VIDEO" VALUES('Le Seigneur des anneaux : les deux tours','Peter Jackson','2002','015','2h58','Américain, Néo-zélandais',NULL);
INSERT INTO "VIDEO" VALUES('Le Seigneur des anneaux : le retour du roi','Peter Jackson','2003','017','3h20','Américain, Néo-zélandais',NULL);
INSERT INTO "VIDEO" VALUES('Le Parrain','Francis Ford Coppola','1972','030','2h55','Américain',NULL);
INSERT INTO "VIDEO" VALUES('Inception','Christopher Nolan','2010','024','2h28','Américain, Britannique',NULL);
INSERT INTO "VIDEO" VALUES('Le Voyage de Chihiro','Hayao Miyazaki','2001','031','2h02','Japonais',NULL);
INSERT INTO "VIDEO" VALUES('Nausicaä de la vallée du vent','Hayao Miyazaki','2006','043','1h56','Japonais',NULL);
INSERT INTO "VIDEO" VALUES('Le Vent se lève','Hayao Miyazaki','2014','041','2h07','Japonais',NULL);
INSERT INTO "VIDEO" VALUES('Princesse Mononoké','Hayao Miyazaki','2000','038','2h15','Japonais',NULL);
CREATE TABLE AUDIO (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  GENRE		 TEXT	 NOT NULL,  PAYS		 TEXT	 NOT NULL, ISEMPRUNT	 BOOLEAN);
INSERT INTO "AUDIO" VALUES('Gotham City','H Magnum','2016','225','Pop-rap','Français',NULL);
INSERT INTO "AUDIO" VALUES('Thriller','Michael Jackson','1982','213','Pop','Américain',NULL);
INSERT INTO "AUDIO" VALUES('Mini World','Indila','2014','223','Pop','Français',NULL);
INSERT INTO "AUDIO" VALUES('Revolution Radio','Green Day','2016','224','Punk-Rock','Américain',NULL);
INSERT INTO "AUDIO" VALUES('Summer Night Town','Morning Musume','1998','219','J-pop','Japonais',NULL);
INSERT INTO "AUDIO" VALUES('Shabondama','Morning Musume','2003','234','J-pop','Japon',NULL);
CREATE TABLE CLIENT (NOM		TEXT	NOT NULL,PRENOM		TEXT	NOT NULL, ADRESSE	TEXT	NOT NULL, PASS		TEXT	NOT NULL );
INSERT INTO "CLIENT" VALUES('Peltier','Floriane','fpeltier@et.esiea.fr','Floriane');
INSERT INTO "CLIENT" VALUES('Mougnin','Louis','mougnin@intech.fr','Louis');
INSERT INTO "CLIENT" VALUES('Larret','Angeline','angelinelarret@hotmail.com','[C@642142a5');
INSERT INTO "CLIENT" VALUES('Djelassi','Hakim','djelassi@et.esiea.fr','[C@1f9c621d');
INSERT INTO "CLIENT" VALUES('Lorenter','Justine','lorenter@et.esiea.fr','[C@39955b5e');
INSERT INTO "CLIENT" VALUES('Lerebourg','Max','lerebourg@et.esiea.fr','[C@ee7a10e');
INSERT INTO "CLIENT" VALUES('Hanotaux','Mathieu','hanotaux@et.esiea.fr','[C@6c30aec7');
INSERT INTO "CLIENT" VALUES('Rojat','Thomas','rojat@et.esiea.fr','[C@76878596');
INSERT INTO "CLIENT" VALUES('Brichler','Mélina','melinabrichler@yahoo.fr','[C@2a486341');
INSERT INTO "CLIENT" VALUES('Naeem','Rabab','rabab.naeem@hotmail.com','[C@79f41bae');
INSERT INTO "CLIENT" VALUES('Sangare','Hassane','sangare@intech.fr','[C@4672dfee');
INSERT INTO "CLIENT" VALUES('Leroy','Augustin','leroy@et.esiea.fr','[C@113e655a');
INSERT INTO "CLIENT" VALUES('Alpou','Cédric','alpou@et.esiea.fr','[C@44945113');
INSERT INTO "CLIENT" VALUES('Doucerain','Mathilde','mathilde.doucerain@gmail.com','[C@1fc8170');
CREATE TABLE LIVRERES (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  PAGES		 TEXT	 NOT NULL,  EDITEUR	 TEXT	 NOT NULL);
CREATE TABLE VIDEORES (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  DUREE		 TEXT	 NOT NULL,  PAYS		 TEXT	 NOT NULL);
INSERT INTO "VIDEORES" VALUES('Django Unchained','Quentin Tarantino','2013','011','2h44','Américain');
INSERT INTO "VIDEORES" VALUES('Forrest Gump','Robert Zemeckis','1994','010','2h20','Américain');
CREATE TABLE AUDIORES (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  GENRE		 TEXT	 NOT NULL,  PAYS		 TEXT	 NOT NULL);
CREATE TABLE LIVRERESV (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  PAGES		 TEXT	 NOT NULL,  EDITEUR	 TEXT	 NOT NULL,  POSSESSEUR	 TEXT	 NOT NULL);
INSERT INTO "LIVRERESV" VALUES('L_étranger','Albert Camus','1942','001','185','Gallimard','Peltier');
CREATE TABLE VIDEORESV (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  DUREE		 TEXT	 NOT NULL,  PAYS		 TEXT	 NOT NULL,  POSSESSEUR	 TEXT	 NOT NULL);
INSERT INTO "VIDEORESV" VALUES('Le Roi Lion','Roger Allers, Rob Minkoff','1994','016','1h29','Américain','Peltier');
INSERT INTO "VIDEORESV" VALUES('Intouchables','Eric Toledano, Olivier Nakache','2011','017','1h52','Français','Mougnin');
CREATE TABLE AUDIORESV (TITRE		 TEXT    NOT NULL, AUTEUR         TEXT    NOT NULL,  ANNEE          TEXT    NOT NULL,  CODE        	 TEXT	 NOT NULL,  GENRE		 TEXT	 NOT NULL,  PAYS		 TEXT	 NOT NULL,  POSSESSEUR	 TEXT	 NOT NULL);
COMMIT;
